# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('cuil', models.CharField(max_length=13, unique=True)),
                ('fecha_nacimiento', models.DateField(help_text='DD/MM/AAAA')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('saldo', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['apellido'],
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(max_length=50)),
                ('medio', models.CharField(choices=[('CRC', 'Cheque recibido comun'), ('CRD', 'Cheque recibido diferido'), ('EF', 'Efectivo'), ('TC', 'Tarjeta de Credito'), ('TF', 'Transferencia')], default='EF', max_length=3)),
            ],
            options={
                'ordering': ['-fecha_alta'],
                'verbose_name': 'Cobro',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('tipo', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], default='B', max_length=1)),
                ('detalle', models.TextField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
            options={
                'ordering': ['-fecha_alta'],
                'verbose_name': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=50)),
                ('monto', models.FloatField(default=0)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Factura')),
            ],
        ),
        migrations.AddField(
            model_name='cobro',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Factura'),
        ),
    ]
